name: Coverage
on:
  push:
    branches:
      - master

jobs:
  Build-on-Linux:
    runs-on: ubuntu-latest
    name: Build on Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install deps
        run: npm install
      - name: Package app
        run: npm run build
      - run: npm install -g azurite
      - name: Coverage
        shell : bash
        env:
          TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run : |
          azurite --silent &
          yarn test --coverage
          bash <(curl -s https://codecov.io/bash) -t ${TOKEN}